config/routes.rb
Rails.application.routes.draw do
  root to: 'gardens#index'

  resources :gardens, only: [:index, :show] do
    # nested because we want the garden id in order to create the plant
    resources :plants, only: [:create]
  end

  # un-nested because we already have the plant id, we don't need the garden id
  resources :plants, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord

  has_many :plants, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden

  validates :name, presence: true, uniqueness: { scope: :garden }
  validates :image_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  # GET /gardens
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  def show
    @garden = Garden.find(params[:id])
    @plant  = Plant.new
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  def create
    # something = Something.new(something_params)
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden

    # if something.save
    # redirect_to somewhere
    # else
    # render something
    # end
    if @plant.save
      redirect_to garden_path(@plant.garden)
    else
      render 'gardens/show'
    end
  end

  def destroy
    @plant = Plant.find(params[:id])

    @plant.destroy

    redirect_to garden_path(@plant.garden)
  end

  private
  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gardens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Banner url</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @gardens.each do |garden| %>
      <tr>
        <td><%= garden.name %></td>
        <td><%= garden.banner_url %></td>
        <td><%= link_to 'Show', garden %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/gardens/show.html.erb
<p id="notice"><%= notice %></p>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @garden.banner_url %>');">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>

<% @garden.plants.each do |plant| %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= plant.image_url %>')">
    <%= plant.name %> <%= link_to 'Dig it up', plant_path(plant), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
<% end %>

<%= simple_form_for([@garden, @plant]) do |f| %>
  <%= f.input :name %>
  <%= f.input :image_url %>
  <%= f.submit 'Create a plant' %>
<% end %>

<%= link_to 'Back', gardens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EvilGardensAndPlants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>